GET http://localhost:3000/api/products/bycategory?category=tec


### crear producto
POST http://localhost:3000/api/products
Content-Type: application/json
atk: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTY0NDE5OTMyNywiZXhwIjoxNjQ0MjAxMTI3fQ.wqLyLW73gM2pPxmy-GpqPEizbll4Zwe_-zSDDJHjS6M

{
    "name":"Memoria RAM DDR4 8GB",
    "price":1000,
    "quantity":50,
    "categoryId":3,
    "description":"Tenis nike"
    
}


### servidor principal
GET http://localhost:3000/api/users/me

### logout
DELETE http://localhost:3001/auth/logout
atk: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTY0NDE5Nzk5MSwiZXhwIjoxNjQ0MTk4MDIxfQ.ay_oWdRpVU5uT6ZucB2U_SYETWZwbzHn6opbpGLjryg




### refresh token
POST http://localhost:3001/auth/token
Content-Type: application/json

{
    "refreshToken":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTY0NDE5OTI5OX0.0uvZavdGtR96yOOS05OEjjzGaXtmAL8aPhoFMaJopBw"
}


### login
POST http://localhost:3001/auth/login
Content-Type: application/json

{
    "email":"robertocastillo945@gmail.com",
    "password":"C@stellan0s12"
}
